"""empty message

Revision ID: 07625901961e
Revises: 4b608c8d2105
Create Date: 2022-08-22 22:19:26.215035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07625901961e'
down_revision = '4b608c8d2105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'users', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'poster_id')
    # ### end Alembic commands ###
