"""empty message

Revision ID: 397430ad30ad
Revises: 
Create Date: 2022-08-15 23:18:52.910187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397430ad30ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'article', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='unique')
    # ### end Alembic commands ###
