"""empty message

Revision ID: afa9ea5b15e6
Revises: 6ad82dcedce2
Create Date: 2022-08-22 21:58:05.900610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa9ea5b15e6'
down_revision = '6ad82dcedce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'users', ['poster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'poster_id')
    # ### end Alembic commands ###
