"""Add unique to Topic, Tag

Revision ID: c622d7600090
Revises: 33dda818c764
Create Date: 2022-08-29 16:59:57.444960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c622d7600090'
down_revision = '33dda818c764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_index(op.f('ix_topic_name'), 'topic', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_name'), table_name='topic')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    # ### end Alembic commands ###
